# Setup Application Environment

# Get Python 3
FROM harmanpa/maven-gcc-python

# Install needed packages
RUN \
  apt-get -y update && \
  apt-get -y install bc net-tools python-setuptools python-dev build-essential libmagic-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN easy_install pip
COPY requirements.txt /root
RUN pip install -r /root/requirements.txt

# Start our sample agent
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY agent/ /usr/src/app/

# Copy user package
COPY package /usr/src/app/

# Supervisor for process management
CMD ["python", "/usr/src/app/agent.py"]

